// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package database

import (
	"context"
)

const refreshTrioMV = `-- name: RefreshTrioMV :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_trio_teams
`

func (q *Queries) RefreshTrioMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshTrioMV)
	return err
}
