// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: character.sql

package database

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO
    characters (image_url_mini, image_url_full, name_kr)
VALUES
    ($1, $2, $3)
RETURNING
    id, name_kr, image_url_mini, image_url_full, created_at, updated_at
`

type CreateCharacterParams struct {
	ImageUrlMini string
	ImageUrlFull string
	NameKr       string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter, arg.ImageUrlMini, arg.ImageUrlFull, arg.NameKr)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.NameKr,
		&i.ImageUrlMini,
		&i.ImageUrlFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE
    id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT
    id, name_kr, image_url_mini, image_url_full, created_at, updated_at
FROM
    characters
WHERE
    id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id int32) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.NameKr,
		&i.ImageUrlMini,
		&i.ImageUrlFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT
    id, name_kr, image_url_mini, image_url_full, created_at, updated_at
FROM
    characters
ORDER BY
    id ASC
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.NameKr,
			&i.ImageUrlMini,
			&i.ImageUrlFull,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchCharacter = `-- name: PatchCharacter :exec
UPDATE characters
SET
    image_url_mini = $2,
    image_url_full = $3,
    name_kr = $4
WHERE
    id = $1
`

type PatchCharacterParams struct {
	ID           int32
	ImageUrlMini string
	ImageUrlFull string
	NameKr       string
}

func (q *Queries) PatchCharacter(ctx context.Context, arg PatchCharacterParams) error {
	_, err := q.db.ExecContext(ctx, patchCharacter,
		arg.ID,
		arg.ImageUrlMini,
		arg.ImageUrlFull,
		arg.NameKr,
	)
	return err
}
