// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: character_weapon.sql

package database

import (
	"context"
)

const createCharacterWeapon = `-- name: CreateCharacterWeapon :one
INSERT INTO
    character_weapons (character_id, weapon_id, position_id, cluster_id)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, character_id, weapon_id, position_id, cluster_id, created_at, updated_at
`

type CreateCharacterWeaponParams struct {
	CharacterID int32
	WeaponID    int32
	PositionID  int32
	ClusterID   int32
}

func (q *Queries) CreateCharacterWeapon(ctx context.Context, arg CreateCharacterWeaponParams) (CharacterWeapon, error) {
	row := q.db.QueryRowContext(ctx, createCharacterWeapon,
		arg.CharacterID,
		arg.WeaponID,
		arg.PositionID,
		arg.ClusterID,
	)
	var i CharacterWeapon
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.WeaponID,
		&i.PositionID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacterWeapon = `-- name: DeleteCharacterWeapon :exec
DELETE FROM character_weapons
WHERE
    id = $1
`

func (q *Queries) DeleteCharacterWeapon(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCharacterWeapon, id)
	return err
}

const getCharacterWeapon = `-- name: GetCharacterWeapon :one
SELECT
    id, character_id, weapon_id, position_id, cluster_id, created_at, updated_at
FROM
    character_weapons
WHERE
    id = $1
`

func (q *Queries) GetCharacterWeapon(ctx context.Context, id int32) (CharacterWeapon, error) {
	row := q.db.QueryRowContext(ctx, getCharacterWeapon, id)
	var i CharacterWeapon
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.WeaponID,
		&i.PositionID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacterWeapons = `-- name: ListCharacterWeapons :many
SELECT
    id, character_id, weapon_id, position_id, cluster_id, created_at, updated_at
FROM
    character_weapons
ORDER BY
    id ASC
`

func (q *Queries) ListCharacterWeapons(ctx context.Context) ([]CharacterWeapon, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterWeapons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterWeapon
	for rows.Next() {
		var i CharacterWeapon
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.WeaponID,
			&i.PositionID,
			&i.ClusterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchCharacterWeapon = `-- name: PatchCharacterWeapon :exec
UPDATE character_weapons
SET
    character_id = $2,
    weapon_id = $3,
    position_id = $4,
    cluster_id = $5
WHERE
    id = $1
`

type PatchCharacterWeaponParams struct {
	ID          int32
	CharacterID int32
	WeaponID    int32
	PositionID  int32
	ClusterID   int32
}

func (q *Queries) PatchCharacterWeapon(ctx context.Context, arg PatchCharacterWeaponParams) error {
	_, err := q.db.ExecContext(ctx, patchCharacterWeapon,
		arg.ID,
		arg.CharacterID,
		arg.WeaponID,
		arg.PositionID,
		arg.ClusterID,
	)
	return err
}
