// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Character struct {
	ID        int32
	Code      int32
	NameKr    string
	ImageUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CharacterWeapon struct {
	ID          int32
	CharacterID int32
	WeaponID    int32
	PositionID  int32
	ClusterID   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CharacterWeaponsStat struct {
	ID        int32
	CwID      int32
	Atk       int32
	Def       int32
	Cc        int32
	Spd       int32
	Sup       int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Cluster struct {
	ID        int32
	Name      string
	ImageUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Game struct {
	ID         int32
	GameCode   int64
	StartedAt  sql.NullTime
	AverageMmr sql.NullInt32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type GameTeam struct {
	ID             int32
	GameID         int32
	TeamID         int32
	GameRank       int32
	TeamKills      int32
	MonsterCredits int32
	GainedMmr      int32
	TeamAvgMmr     int32
	TotalTime      int32
	TimesID        sql.NullInt32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GameTeamCw struct {
	ID         int32
	GameTeamID int32
	CwID       int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Position struct {
	ID        int32
	Name      string
	ImageUrl  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tier struct {
	ID        int32
	Imageurl  string
	Name      string
	Mmr       int32
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Time struct {
	ID        int32
	No        int32
	Name      string
	Seconds   int32
	StartTime int32
	EndTime   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Weapon struct {
	ID        int32
	Code      int32
	NameKr    string
	ImageUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
