// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tier.sql

package database

import (
	"context"
)

const createTier = `-- name: CreateTier :one
INSERT INTO
    tiers (image_url, name, mmr)
VALUES
    ($1, $2, $3)
RETURNING
    id, image_url, name, mmr, created_at, updated_at
`

type CreateTierParams struct {
	ImageUrl string
	Name     string
	Mmr      int32
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (Tier, error) {
	row := q.db.QueryRowContext(ctx, createTier, arg.ImageUrl, arg.Name, arg.Mmr)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.Name,
		&i.Mmr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTier = `-- name: DeleteTier :exec
DELETE FROM tiers
WHERE
    id = $1
`

func (q *Queries) DeleteTier(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTier, id)
	return err
}

const getTier = `-- name: GetTier :one
SELECT
    id, image_url, name, mmr, created_at, updated_at
FROM
    tiers
WHERE
    id = $1
`

func (q *Queries) GetTier(ctx context.Context, id int32) (Tier, error) {
	row := q.db.QueryRowContext(ctx, getTier, id)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.Name,
		&i.Mmr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTiers = `-- name: ListTiers :many
SELECT
    id, image_url, name, mmr, created_at, updated_at
FROM
    tiers
ORDER BY
    id ASC
`

func (q *Queries) ListTiers(ctx context.Context) ([]Tier, error) {
	rows, err := q.db.QueryContext(ctx, listTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tier
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.Name,
			&i.Mmr,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchTier = `-- name: PatchTier :exec
UPDATE tiers
SET
    image_url = $2,
    name = $3,
    mmr = $4
WHERE
    id = $1
`

type PatchTierParams struct {
	ID       int32
	ImageUrl string
	Name     string
	Mmr      int32
}

func (q *Queries) PatchTier(ctx context.Context, arg PatchTierParams) error {
	_, err := q.db.ExecContext(ctx, patchTier,
		arg.ID,
		arg.ImageUrl,
		arg.Name,
		arg.Mmr,
	)
	return err
}
