// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time.sql

package database

import (
	"context"
)

const createTime = `-- name: CreateTime :one
INSERT INTO
    times (no, name, seconds, start_time, end_time)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, no, name, seconds, start_time, end_time, created_at, updated_at
`

type CreateTimeParams struct {
	No        int32
	Name      string
	Seconds   int32
	StartTime int32
	EndTime   int32
}

func (q *Queries) CreateTime(ctx context.Context, arg CreateTimeParams) (Time, error) {
	row := q.db.QueryRowContext(ctx, createTime,
		arg.No,
		arg.Name,
		arg.Seconds,
		arg.StartTime,
		arg.EndTime,
	)
	var i Time
	err := row.Scan(
		&i.ID,
		&i.No,
		&i.Name,
		&i.Seconds,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTime = `-- name: DeleteTime :exec
DELETE FROM times
WHERE
    id = $1
`

func (q *Queries) DeleteTime(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTime, id)
	return err
}

const getTime = `-- name: GetTime :one
SELECT
    id, no, name, seconds, start_time, end_time, created_at, updated_at
FROM
    times
WHERE
    id = $1
`

func (q *Queries) GetTime(ctx context.Context, id int32) (Time, error) {
	row := q.db.QueryRowContext(ctx, getTime, id)
	var i Time
	err := row.Scan(
		&i.ID,
		&i.No,
		&i.Name,
		&i.Seconds,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimes = `-- name: ListTimes :many
SELECT
    id, no, name, seconds, start_time, end_time, created_at, updated_at
FROM
    times
ORDER BY
    id ASC
`

func (q *Queries) ListTimes(ctx context.Context) ([]Time, error) {
	rows, err := q.db.QueryContext(ctx, listTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Time
	for rows.Next() {
		var i Time
		if err := rows.Scan(
			&i.ID,
			&i.No,
			&i.Name,
			&i.Seconds,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchTime = `-- name: PatchTime :exec
UPDATE times
SET
    name = $2,
    seconds = $3,
    start_time = $4,
    end_time = $5
WHERE
    id = $1
`

type PatchTimeParams struct {
	ID        int32
	Name      string
	Seconds   int32
	StartTime int32
	EndTime   int32
}

func (q *Queries) PatchTime(ctx context.Context, arg PatchTimeParams) error {
	_, err := q.db.ExecContext(ctx, patchTime,
		arg.ID,
		arg.Name,
		arg.Seconds,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}
