package erapi

// type TotalGame struct {
// 	UserGames []UserGame `json:"userGames"`
// }

type UserGame struct {
	UserNum          int            `json:"userNum"`
	Nickname         string         `json:"nickname"`
	GameID           int            `json:"gameId"`
	SeasonID         int            `json:"seasonId"`
	MatchingMode     int            `json:"matchingMode"`
	MatchingTeamMode int            `json:"matchingTeamMode"`
	CharacterNum     int            `json:"characterNum"`
	SkinCode         int            `json:"skinCode"`
	CharacterLevel   int            `json:"characterLevel"`
	GameRank         int            `json:"gameRank"`
	PlayerKill       int            `json:"playerKill"`
	PlayerAssistant  int            `json:"playerAssistant"`
	MonsterKill      int            `json:"monsterKill"`
	BestWeapon       int            `json:"bestWeapon"`
	BestWeaponLevel  int            `json:"bestWeaponLevel"`
	MasteryLevel     map[string]int `json:"masteryLevel"`
	// Equipment Code = 0 weapon, 1 clothes, 2 hat, 3 arm, 4 leg
	// Equipment struct {
	// 	Num0 int `json:"0"`
	// 	Num1 int `json:"1"`
	// 	Num2 int `json:"2"`
	// 	Num3 int `json:"3"`
	// 	Num4 int `json:"4"`
	// } `json:"equipment"`
	Equipment map[string]int `json:"equipment"`

	// Grade Code = 0 common, 1 uncommon, 2 rare, 3 epic, 4 legendary, 5 mythic
	// EquipmentGrade struct {
	// 	Num0 int `json:"0"`
	// 	Num1 int `json:"1"`
	// 	Num2 int `json:"2"`
	// 	Num3 int `json:"3"`
	// 	Num4 int `json:"4"`
	// } `json:"equipmentGrade"`
	EquipmentGrade                map[string]int `json:"equipmentGrade"`
	VersionMajor                  int            `json:"versionMajor"`
	VersionMinor                  int            `json:"versionMinor"`
	Language                      string         `json:"language"`
	SkillLevelInfo                map[string]int `json:"skillLevelInfo"`
	SkillOrderInfo                map[string]int `json:"skillOrderInfo"`
	ServerName                    string         `json:"serverName"`
	MaxHp                         int            `json:"maxHp"`
	MaxSp                         int            `json:"maxSp"`
	AttackPower                   int            `json:"attackPower"`
	Defense                       int            `json:"defense"`
	HpRegen                       float64        `json:"hpRegen"`
	SpRegen                       float64        `json:"spRegen"`
	AttackSpeed                   float64        `json:"attackSpeed"`
	MoveSpeed                     float64        `json:"moveSpeed"`
	OutOfCombatMoveSpeed          float64        `json:"outOfCombatMoveSpeed"`
	SightRange                    float64        `json:"sightRange"`
	AttackRange                   float64        `json:"attackRange"`
	CriticalStrikeChance          float64        `json:"criticalStrikeChance"`
	CriticalStrikeDamage          float64        `json:"criticalStrikeDamage"`
	CoolDownReduction             float64        `json:"coolDownReduction"`
	LifeSteal                     float64        `json:"lifeSteal"`
	NormalLifeSteal               float64        `json:"normalLifeSteal"`
	SkillLifeSteal                float64        `json:"skillLifeSteal"`
	AmplifierToMonster            float64        `json:"amplifierToMonster"`
	TrapDamage                    float64        `json:"trapDamage"`
	BonusCoin                     int            `json:"bonusCoin"`
	GainExp                       int            `json:"gainExp"`
	BaseExp                       int            `json:"baseExp"`
	BonusExp                      int            `json:"bonusExp"`
	StartDtm                      string         `json:"startDtm"`
	Duration                      int            `json:"duration"`
	PlayTime                      int            `json:"playTime"`
	WatchTime                     int            `json:"watchTime"`
	TotalTime                     int            `json:"totalTime"`
	SurvivableTime                int            `json:"survivableTime"`
	BotAdded                      int            `json:"botAdded"`
	BotRemain                     int            `json:"botRemain"`
	RestrictedAreaAccelerated     int            `json:"restrictedAreaAccelerated"`
	SafeAreas                     int            `json:"safeAreas"`
	TeamNumber                    int            `json:"teamNumber"`
	PreMade                       int            `json:"preMade"`
	EventMissionResult            map[string]int `json:"eventMissionResult"`
	GainedNormalMmrKFactor        float64        `json:"gainedNormalMmrKFactor"`
	Victory                       int            `json:"victory"`
	CraftUncommon                 int            `json:"craftUncommon"`
	CraftRare                     int            `json:"craftRare"`
	CraftEpic                     int            `json:"craftEpic"`
	CraftLegend                   int            `json:"craftLegend"`
	DamageToPlayer                int            `json:"damageToPlayer"`
	DamageToPlayerTrap            int            `json:"damageToPlayer_trap"`
	DamageToPlayerBasic           int            `json:"damageToPlayer_basic"`
	DamageToPlayerSkill           int            `json:"damageToPlayer_skill"`
	DamageToPlayerItemSkill       int            `json:"damageToPlayer_itemSkill"`
	DamageToPlayerDirect          int            `json:"damageToPlayer_direct"`
	DamageToPlayerUniqueSkill     int            `json:"damageToPlayer_uniqueSkill"`
	DamageFromPlayer              int            `json:"damageFromPlayer"`
	DamageFromPlayerTrap          int            `json:"damageFromPlayer_trap"`
	DamageFromPlayerBasic         int            `json:"damageFromPlayer_basic"`
	DamageFromPlayerSkill         int            `json:"damageFromPlayer_skill"`
	DamageFromPlayerItemSkill     int            `json:"damageFromPlayer_itemSkill"`
	DamageFromPlayerDirect        int            `json:"damageFromPlayer_direct"`
	DamageFromPlayerUniqueSkill   int            `json:"damageFromPlayer_uniqueSkill"`
	DamageToMonster               int            `json:"damageToMonster"`
	DamageToMonsterTrap           int            `json:"damageToMonster_trap"`
	DamageToMonsterBasic          int            `json:"damageToMonster_basic"`
	DamageToMonsterSkill          int            `json:"damageToMonster_skill"`
	DamageToMonsterItemSkill      int            `json:"damageToMonster_itemSkill"`
	DamageToMonsterDirect         int            `json:"damageToMonster_direct"`
	DamageToMonsterUniqueSkill    int            `json:"damageToMonster_uniqueSkill"`
	DamageFromMonster             int            `json:"damageFromMonster"`
	DamageToPlayerShield          int            `json:"damageToPlayer_Shield"`
	DamageOffsetedByShieldPlayer  int            `json:"damageOffsetedByShield_Player"`
	DamageOffsetedByShieldMonster int            `json:"damageOffsetedByShield_Monster"`
	KillMonsters                  map[string]int `json:"killMonsters"`
	HealAmount                    int            `json:"healAmount"`
	TeamRecover                   int            `json:"teamRecover"`
	ProtectAbsorb                 int            `json:"protectAbsorb"`
	AddSurveillanceCamera         int            `json:"addSurveillanceCamera"`
	AddTelephotoCamera            int            `json:"addTelephotoCamera"`
	RemoveSurveillanceCamera      int            `json:"removeSurveillanceCamera"`
	RemoveTelephotoCamera         int            `json:"removeTelephotoCamera"`
	UseHyperLoop                  int            `json:"useHyperLoop"`
	UseSecurityConsole            int            `json:"useSecurityConsole"`
	GiveUp                        int            `json:"giveUp"`
	TeamSpectator                 int            `json:"teamSpectator"`
	RouteIDOfStart                int            `json:"routeIdOfStart"`
	RouteSlotID                   int            `json:"routeSlotId"`
	PlaceOfStart                  string         `json:"placeOfStart"`
	MatchSize                     int            `json:"matchSize"`
	TeamKill                      int            `json:"teamKill"`
	TotalFieldKill                int            `json:"totalFieldKill"`
	AccountLevel                  int            `json:"accountLevel"`
	KillerUserNum                 int            `json:"killerUserNum"`
	Killer                        string         `json:"killer"`
	KillDetail                    string         `json:"killDetail"`
	CauseOfDeath                  string         `json:"causeOfDeath"`
	PlaceOfDeath                  string         `json:"placeOfDeath"`
	KillerCharacter               string         `json:"killerCharacter"`
	KillerWeapon                  string         `json:"killerWeapon"`
	KillerUserNum2                int            `json:"killerUserNum2"`
	Killer2                       string         `json:"killer2,omitempty"`
	KillDetail2                   string         `json:"killDetail2,omitempty"`
	CauseOfDeath2                 string         `json:"causeOfDeath2,omitempty"`
	PlaceOfDeath2                 string         `json:"placeOfDeath2,omitempty"`
	KillerCharacter2              string         `json:"killerCharacter2,omitempty"`
	KillerWeapon2                 string         `json:"killerWeapon2,omitempty"`
	KillerUserNum3                int            `json:"killerUserNum3"`
	Killer3                       string         `json:"killer3,omitempty"`
	KillDetail3                   string         `json:"killDetail3,omitempty"`
	CauseOfDeath3                 string         `json:"causeOfDeath3,omitempty"`
	PlaceOfDeath3                 string         `json:"placeOfDeath3,omitempty"`
	KillerCharacter3              string         `json:"killerCharacter3,omitempty"`
	KillerWeapon3                 string         `json:"killerWeapon3,omitempty"`
	FishingCount                  int            `json:"fishingCount"`
	UseEmoticonCount              int            `json:"useEmoticonCount"`
	ExpireDtm                     string         `json:"expireDtm"`
	TraitFirstCore                int            `json:"traitFirstCore"`
	TraitFirstSub                 []int          `json:"traitFirstSub"`
	TraitSecondSub                []int          `json:"traitSecondSub"`
	AirSupplyOpenCount            []int          `json:"airSupplyOpenCount"`
	FoodCraftCount                []int          `json:"foodCraftCount"`
	BeverageCraftCount            []int          `json:"beverageCraftCount"`
	RankPoint                     int            `json:"rankPoint"`
	TotalTurbineTakeOver          int            `json:"totalTurbineTakeOver"`
	UsedNormalHealPack            int            `json:"usedNormalHealPack"`
	UsedReinforcedHealPack        int            `json:"usedReinforcedHealPack"`
	UsedNormalShieldPack          int            `json:"usedNormalShieldPack"`
	UsedReinforceShieldPack       int            `json:"usedReinforceShieldPack"`
	TotalVFCredits                []int          `json:"totalVFCredits"`
	ActivelyGainedCredits         int            `json:"activelyGainedCredits"`
	UsedVFCredits                 []int          `json:"usedVFCredits"`
	SumUsedVFCredits              int            `json:"sumUsedVFCredits"`
	CraftMythic                   int            `json:"craftMythic"`
	PlayerDeaths                  int            `json:"playerDeaths"`
	KillGamma                     bool           `json:"killGamma"`
	ScoredPoint                   []int          `json:"scoredPoint"`
	KillDetails                   string         `json:"killDetails"`
	DeathDetails                  string         `json:"deathDetails"`
	KillsPhaseOne                 int            `json:"killsPhaseOne"`
	KillsPhaseTwo                 int            `json:"killsPhaseTwo"`
	KillsPhaseThree               int            `json:"killsPhaseThree"`
	DeathsPhaseOne                int            `json:"deathsPhaseOne"`
	DeathsPhaseTwo                int            `json:"deathsPhaseTwo"`
	DeathsPhaseThree              int            `json:"deathsPhaseThree"`
	UsedPairLoop                  int            `json:"usedPairLoop"`
	CcTimeToPlayer                float64        `json:"ccTimeToPlayer"`
	CreditSource                  struct {
		PreliminaryPhase                    float64 `json:"PreliminaryPhase"`
		TimeElapsedCompensationByMiliSecond float64 `json:"TimeElapsedCompensationByMiliSecond"`
		KillChicken                         float64 `json:"KillChicken"`
		KioskRemoteDroneMySelf              float64 `json:"KioskRemoteDroneMySelf"`
		TimeElapsedCreditBonusByMiliSecond  float64 `json:"TimeElapsedCreditBonusByMiliSecond"`
		KillBat                             float64 `json:"KillBat"`
		KillBoar                            float64 `json:"KillBoar"`
		KillWolf                            float64 `json:"KillWolf"`
		GoldSecurityConsoleAccess           float64 `json:"GoldSecurityConsoleAccess"`
		KillWildDog                         float64 `json:"KillWildDog"`
		KillMutantChicken                   float64 `json:"KillMutantChicken"`
		KillBear                            float64 `json:"KillBear"`
		KillRaven                           float64 `json:"KillRaven"`
		KillMutantRaven                     float64 `json:"KillMutantRaven"`
		KillMutantBoar                      float64 `json:"KillMutantBoar"`
		KillAssistDivideContribute          float64 `json:"KillAssistDivideContribute"`
		KillMutantWolf                      float64 `json:"KillMutantWolf"`
		KillMutantWildDog                   float64 `json:"KillMutantWildDog"`
		ItemBounty                          float64 `json:"ItemBounty"`
		KioskSpecialMaterial                float64 `json:"KioskSpecialMaterial"`
		KillDrone                           float64 `json:"KillDrone"`
		ItemBountyByItemCode                float64 `json:"ItemBountyByItemCode"`
		KillMutantBat                       float64 `json:"KillMutantBat"`
		KioskResurrection                   float64 `json:"KioskResurrection"`
	} `json:"creditSource"`
	BoughtInfusion         string `json:"boughtInfusion"`
	ItemTransferredConsole []int  `json:"itemTransferredConsole"`
	ItemTransferredDrone   []int  `json:"itemTransferredDrone"`
	EscapeState            int    `json:"escapeState"`
	TotalDoubleKill        int    `json:"totalDoubleKill"`
	TotalTripleKill        int    `json:"totalTripleKill"`
	TotalQuadraKill        int    `json:"totalQuadraKill"`
	TotalExtraKill         int    `json:"totalExtraKill"`
	CollectItemForLog      []int  `json:"collectItemForLog"`
	// Equipment Code = 0 weapon, 1 clothes, 2 hat, 3 arm, 4 leg
	// EquipFirstItemForLog   struct {
	// 	Num0 []int `json:"0"`
	// 	Num1 []int `json:"1"`
	// 	Num2 []int `json:"2"`
	// 	Num3 []int `json:"3"`
	// 	Num4 []int `json:"4"`
	// } `json:"equipFirstItemForLog"`

	EquipFirstItemForLog                    map[string][]int `json:"equipFirstItemForLog"`
	BattleZone1AreaCode                     int              `json:"battleZone1AreaCode"`
	BattleZone1BattleMark                   int              `json:"battleZone1BattleMark"`
	BattleZone1ItemCode                     []any            `json:"battleZone1ItemCode"`
	BattleZone2AreaCode                     int              `json:"battleZone2AreaCode"`
	BattleZone2BattleMark                   int              `json:"battleZone2BattleMark"`
	BattleZone2ItemCode                     []any            `json:"battleZone2ItemCode"`
	BattleZone3AreaCode                     int              `json:"battleZone3AreaCode"`
	BattleZone3BattleMark                   int              `json:"battleZone3BattleMark"`
	BattleZone3ItemCode                     []any            `json:"battleZone3ItemCode"`
	BattleZonePlayerKill                    int              `json:"battleZonePlayerKill"`
	BattleZoneDeaths                        int              `json:"battleZoneDeaths"`
	BattleZone1Winner                       int              `json:"battleZone1Winner"`
	BattleZone2Winner                       int              `json:"battleZone2Winner"`
	BattleZone3Winner                       int              `json:"battleZone3Winner"`
	BattleZone1BattleMarkCount              int              `json:"battleZone1BattleMarkCount"`
	BattleZone2BattleMarkCount              int              `json:"battleZone2BattleMarkCount"`
	BattleZone3BattleMarkCount              int              `json:"battleZone3BattleMarkCount"`
	TacticalSkillGroup                      int              `json:"tacticalSkillGroup"`
	TacticalSkillLevel                      int              `json:"tacticalSkillLevel"`
	TotalGainVFCredit                       int              `json:"totalGainVFCredit"`
	KillPlayerGainVFCredit                  int              `json:"killPlayerGainVFCredit"`
	KillChickenGainVFCredit                 int              `json:"killChickenGainVFCredit"`
	KillBoarGainVFCredit                    int              `json:"killBoarGainVFCredit"`
	KillWildDogGainVFCredit                 int              `json:"killWildDogGainVFCredit"`
	KillWolfGainVFCredit                    int              `json:"killWolfGainVFCredit"`
	KillBearGainVFCredit                    int              `json:"killBearGainVFCredit"`
	KillOmegaGainVFCredit                   int              `json:"killOmegaGainVFCredit"`
	KillBatGainVFCredit                     int              `json:"killBatGainVFCredit"`
	KillWicklineGainVFCredit                int              `json:"killWicklineGainVFCredit"`
	KillAlphaGainVFCredit                   int              `json:"killAlphaGainVFCredit"`
	KillItemBountyGainVFCredit              int              `json:"killItemBountyGainVFCredit"`
	KillDroneGainVFCredit                   int              `json:"killDroneGainVFCredit"`
	KillGammaGainVFCredit                   int              `json:"killGammaGainVFCredit"`
	KillTurretGainVFCredit                  int              `json:"killTurretGainVFCredit"`
	ItemShredderGainVFCredit                int              `json:"itemShredderGainVFCredit"`
	TotalUseVFCredit                        int              `json:"totalUseVFCredit"`
	RemoteDroneUseVFCreditMySelf            int              `json:"remoteDroneUseVFCreditMySelf"`
	RemoteDroneUseVFCreditAlly              int              `json:"remoteDroneUseVFCreditAlly"`
	TransferConsoleFromMaterialUseVFCredit  int              `json:"transferConsoleFromMaterialUseVFCredit"`
	TransferConsoleFromEscapeKeyUseVFCredit int              `json:"transferConsoleFromEscapeKeyUseVFCredit"`
	TransferConsoleFromRevivalUseVFCredit   int              `json:"transferConsoleFromRevivalUseVFCredit"`
	TacticalSkillUpgradeUseVFCredit         int              `json:"tacticalSkillUpgradeUseVFCredit"`
	InfusionReRollUseVFCredit               int              `json:"infusionReRollUseVFCredit"`
	InfusionTraitUseVFCredit                int              `json:"infusionTraitUseVFCredit"`
	InfusionRelicUseVFCredit                int              `json:"infusionRelicUseVFCredit"`
	InfusionStoreUseVFCredit                int              `json:"infusionStoreUseVFCredit"`
	TeamElimination                         int              `json:"teamElimination"`
	TeamDown                                int              `json:"teamDown"`
	TeamBattleZoneDown                      int              `json:"teamBattleZoneDown"`
	TeamRepeatDown                          int              `json:"teamRepeatDown"`
	AdaptiveForce                           int              `json:"adaptiveForce"`
	AdaptiveForceAttack                     int              `json:"adaptiveForceAttack"`
	AdaptiveForceAmplify                    int              `json:"adaptiveForceAmplify"`
	SkillAmp                                int              `json:"skillAmp"`
	CampFireCraftUncommon                   int              `json:"campFireCraftUncommon"`
	CampFireCraftRare                       int              `json:"campFireCraftRare"`
	CampFireCraftEpic                       int              `json:"campFireCraftEpic"`
	CampFireCraftLegendary                  int              `json:"campFireCraftLegendary"`
	CobaltRandomPickRemoveCharacter         int              `json:"cobaltRandomPickRemoveCharacter"`
	TacticalSkillUseCount                   int              `json:"tacticalSkillUseCount"`
	CreditRevivalCount                      int              `json:"creditRevivalCount"`
	CreditRevivedOthersCount                int              `json:"creditRevivedOthersCount"`
	TimeSpentInBriefingRoom                 int              `json:"timeSpentInBriefingRoom"`
	CrGetAnimal                             int              `json:"crGetAnimal"`
	CrGetMutant                             int              `json:"crGetMutant"`
	CrGetPhaseStart                         int              `json:"crGetPhaseStart"`
	CrGetKill                               int              `json:"crGetKill"`
	CrGetAssist                             int              `json:"crGetAssist"`
	CrGetTimeElapsed                        int              `json:"crGetTimeElapsed"`
	CrGetCreditBonus                        int              `json:"crGetCreditBonus"`
	CrUseRemoteDrone                        int              `json:"crUseRemoteDrone"`
	CrUseUpgradeTacticalSkill               int              `json:"crUseUpgradeTacticalSkill"`
	CrUseTreeOfLife                         int              `json:"crUseTreeOfLife"`
	CrUseMeteorite                          int              `json:"crUseMeteorite"`
	CrUseMythril                            int              `json:"crUseMythril"`
	CrUseForceCore                          int              `json:"crUseForceCore"`
	CrUseVFBloodSample                      int              `json:"crUseVFBloodSample"`
	CrUseActivationModule                   int              `json:"crUseActivationModule"`
	CrUseRootkit                            int              `json:"crUseRootkit"`
	MmrGainInGame                           int              `json:"mmrGainInGame"`
	MmrLossEntryCost                        int              `json:"mmrLossEntryCost"`
	MmrAvg                                  int              `json:"mmrAvg"`
	PremadeMatchingType                     int              `json:"premadeMatchingType"`
	ViewContribution                        int              `json:"viewContribution"`
	UseReconDrone                           int              `json:"useReconDrone"`
	UseEmpDrone                             int              `json:"useEmpDrone"`
	ExceptPreMadeTeam                       bool             `json:"exceptPreMadeTeam"`
	TerminateCount                          int              `json:"terminateCount"`
	ClutchCount                             int              `json:"clutchCount"`
	UnknownKill                             int              `json:"unknownKill"`
	MainWeather                             int              `json:"mainWeather"`
	SubWeather                              int              `json:"subWeather"`
	ActiveInstallation                      map[string]int   `json:"activeInstallation"`
	UseGuideRobot                           int              `json:"useGuideRobot"`
	GuideRobotRadial                        int              `json:"guideRobotRadial"`
	GuideRobotFlagShip                      int              `json:"guideRobotFlagShip"`
	GuideRobotSignature                     int              `json:"guideRobotSignature"`
	CrGetByGuideRobot                       int              `json:"crGetByGuideRobot"`
	DamageToGuideRobot                      int              `json:"damageToGuideRobot"`
	GetBuffCubeRed                          int              `json:"getBuffCubeRed"`
	GetBuffCubePurple                       int              `json:"getBuffCubePurple"`
	GetBuffCubeGreen                        int              `json:"getBuffCubeGreen"`
	GetBuffCubeGold                         int              `json:"getBuffCubeGold"`
	GetBuffCubeSkyBlue                      int              `json:"getBuffCubeSkyBlue"`
	SumGetBuffCube                          int              `json:"sumGetBuffCube"`
	SquadRumbleRank                         int              `json:"squadRumbleRank"`
	TeamDownCanNotEliminate                 int              `json:"teamDownCanNotEliminate"`
	TeamDownCanEliminate                    int              `json:"teamDownCanEliminate"`
	TeamRepeatDownCanNotEliminate           int              `json:"teamRepeatDownCanNotEliminate"`
	TeamRepeatDownCanEliminate              int              `json:"teamRepeatDownCanEliminate"`
	TerminateCountCanNotEliminate           int              `json:"terminateCountCanNotEliminate"`
	BreakCount                              int              `json:"breakCount"`
	EnterDimensionRift                      int              `json:"enterDimensionRift"`
	EnterDimensionEmpoweredRift             int              `json:"enterDimensionEmpoweredRift"`
	WinFromDimensionRift                    int              `json:"winFromDimensionRift"`
	WinFromDimensionEmpoweredRift           int              `json:"winFromDimensionEmpoweredRift"`
	EnterTurbulentRift                      int              `json:"enterTurbulentRift"`
	IsLeavingBeforeCreditRevivalTerminate   bool             `json:"isLeavingBeforeCreditRevivalTerminate"`
}
