package erapi

type item struct {
	AdaptiveForce                                      int    `json:"adaptiveForce"`
	AdaptiveForceByLevel                               int    `json:"adaptiveForceByLevel"`
	AlertInSpectator                                   bool   `json:"alertInSpectator"`
	AttackPower                                        int    `json:"attackPower"`
	AttackPowerByLv                                    int    `json:"attackPowerByLv"`
	AttackRange                                        int    `json:"attackRange"`
	AttackSpeedRatio                                   int    `json:"attackSpeedRatio"`
	AttackSpeedRatioByLv                               int    `json:"attackSpeedRatioByLv"`
	AutoDisappear                                      bool   `json:"autoDisappear"`
	Code                                               int    `json:"code"`
	Consumable                                         bool   `json:"consumable"`
	CooldownLimit                                      int    `json:"cooldownLimit"`
	CooldownReduction                                  int    `json:"cooldownReduction"`
	CorpseAndWorldItemEffectEnable                     bool   `json:"corpseAndWorldItemEffectEnable"`
	CraftAnimTrigger                                   string `json:"craftAnimTrigger"`
	CreditValueWhenConvertedToBounty                   int    `json:"creditValueWhenConvertedToBounty"`
	CriticalStrikeChance                               int    `json:"criticalStrikeChance"`
	CriticalStrikeDamage                               int    `json:"criticalStrikeDamage"`
	Defense                                            int    `json:"defense"`
	DefenseByLv                                        int    `json:"defenseByLv"`
	Exchange                                           int    `json:"exchange"`
	ExclusiveProducer                                  int    `json:"exclusiveProducer"`
	GradeBgOverride                                    string `json:"gradeBgOverride"`
	HealerGiveHpHealRatio                              int    `json:"healerGiveHpHealRatio"`
	HpHealedIncreaseRatio                              int    `json:"hpHealedIncreaseRatio"`
	HpRegen                                            int    `json:"hpRegen"`
	HpRegenRatio                                       int    `json:"hpRegenRatio"`
	IncreaseBasicAttackDamage                          int    `json:"increaseBasicAttackDamage"`
	IncreaseBasicAttackDamageByLv                      int    `json:"increaseBasicAttackDamageByLv"`
	IncreaseBasicAttackDamageRatio                     int    `json:"increaseBasicAttackDamageRatio"`
	IncreaseBasicAttackDamageRatioByLv                 int    `json:"increaseBasicAttackDamageRatioByLv"`
	InitialCount                                       int    `json:"initialCount"`
	IsCanMonsterAreaItemDrop                           bool   `json:"isCanMonsterAreaItemDrop"`
	IsCompletedItem                                    bool   `json:"isCompletedItem"`
	IsRemovedFromPlayerCorpseInventoryWhenPlayerKilled bool   `json:"isRemovedFromPlayerCorpseInventoryWhenPlayerKilled"`
	ItemGrade                                          string `json:"itemGrade"`
	ItemType                                           string `json:"itemType"`
	ItemUsableType                                     string `json:"itemUsableType"`
	ItemUsableValueList                                int    `json:"itemUsableValueList"`
	LifeSteal                                          int    `json:"lifeSteal"`
	MakeCustomAction                                   string `json:"makeCustomAction"`
	MakeMaterial1                                      int    `json:"makeMaterial1"`
	MakeMaterial2                                      int    `json:"makeMaterial2"`
	ManufacturableType                                 int    `json:"manufacturableType"`
	MarkingType                                        string `json:"markingType"`
	MaxHp                                              int    `json:"maxHp"`
	MaxHpByLv                                          int    `json:"maxHpByLv"`
	MaxSP                                              int    `json:"maxSP"`
	ModeType                                           int    `json:"modeType"`
	MoveSpeed                                          int    `json:"moveSpeed"`
	MoveSpeedOutOfCombat                               int    `json:"moveSpeedOutOfCombat"`
	MoveSpeedRatio                                     int    `json:"moveSpeedRatio"`
	Name                                               string `json:"name"`
	NormalLifeSteal                                    int    `json:"normalLifeSteal"`
	NotDisarm                                          bool   `json:"notDisarm"`
	PenetrationDefense                                 int    `json:"penetrationDefense"`
	PenetrationDefenseRatio                            int    `json:"penetrationDefenseRatio"`
	PreventBasicAttackDamaged                          int    `json:"preventBasicAttackDamaged"`
	PreventBasicAttackDamagedByLv                      int    `json:"preventBasicAttackDamagedByLv"`
	PreventBasicAttackDamagedRatio                     int    `json:"preventBasicAttackDamagedRatio"`
	PreventBasicAttackDamagedRatioByLv                 int    `json:"preventBasicAttackDamagedRatioByLv"`
	PreventCriticalStrikeDamaged                       int    `json:"preventCriticalStrikeDamaged"`
	PreventSkillDamaged                                int    `json:"preventSkillDamaged"`
	PreventSkillDamagedByLv                            int    `json:"preventSkillDamagedByLv"`
	PreventSkillDamagedRatio                           int    `json:"preventSkillDamagedRatio"`
	PreventSkillDamagedRatioByLv                       int    `json:"preventSkillDamagedRatioByLv"`
	RestoreItemWhenResurrected                         bool   `json:"restoreItemWhenResurrected"`
	ShowInItemBook                                     bool   `json:"showInItemBook"`
	SightRange                                         int    `json:"sightRange"`
	SkillAmp                                           int    `json:"skillAmp"`
	SkillAmpByLevel                                    int    `json:"skillAmpByLevel"`
	SkillAmpRatio                                      int    `json:"skillAmpRatio"`
	SkillAmpRatioByLevel                               int    `json:"skillAmpRatioByLevel"`
	SkillLifeSteal                                     int    `json:"skillLifeSteal"`
	SlowResistRatio                                    int    `json:"slowResistRatio"`
	SpRegen                                            int    `json:"spRegen"`
	SpRegenRatio                                       int    `json:"spRegenRatio"`
	Stackable                                          int    `json:"stackable"`
	TacticalCooldownReduction                          int    `json:"tacticalCooldownReduction"`
	TrapDamageReduce                                   int    `json:"trapDamageReduce"`
	TrapDamageReduceRatio                              int    `json:"trapDamageReduceRatio"`
	UltCooldownReduction                               int    `json:"ultCooldownReduction"`
	UniqueAttackRange                                  int    `json:"uniqueAttackRange"`
	UniqueCooldownLimit                                int    `json:"uniqueCooldownLimit"`
	UniqueHpHealedIncreaseRatio                        int    `json:"uniqueHpHealedIncreaseRatio"`
	UniqueLifeSteal                                    int    `json:"uniqueLifeSteal"`
	UniqueMoveSpeed                                    int    `json:"uniqueMoveSpeed"`
	UniquePenetrationDefense                           int    `json:"uniquePenetrationDefense"`
	UniquePenetrationDefenseRatio                      int    `json:"uniquePenetrationDefenseRatio"`
	UniqueSkillAmpRatio                                int    `json:"uniqueSkillAmpRatio"`
	UniqueTenacity                                     int    `json:"uniqueTenacity"`
	WeaponCooldownReduction                            int    `json:"weaponCooldownReduction"`
	WeaponType                                         string `json:"weaponType"`
}
