-- +goose Up
CREATE TABLE games (
    id SERIAL PRIMARY KEY,
    game_id INT NOT NULL,
    average_mmr INT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE games;
